### ISSUE TITLE
Error when destroying select2 DOM

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [aldeed/meteor-autoform-select2#44]
Hi, when my select2 element is destroyed (it's rendered inside a if statement, so when it turns false, it is destroyed) i get the error on console:
The select2('destroy') method was called on an element that is not using Select2.

Do u guys know how to solve it? thanks

**Comment by lynchem** [comment]
+1

**Comment by smelnyk** [comment]
+1

**Comment by Omar-allahham** [comment]
I have the same problem ...

**Comment by skirunman** [comment]
Same problem here

**Comment by shkomg** [comment]
looks like it is related to this file:

https://github.com/aldeed/meteor-autoform-select2/search?utf8=%E2%9C%93&q=select2%28%27destroy%27%29&type=Code

@aldeed, to fix it, I think we need to change Line 175 to this one 
```if (this.view && this.view._domrange && this.$('select').data('select2')) {```

I'll try to make push request ASAP

**Comment by thearabbit** [comment]
I have the same problem.

**Comment by floriandotorg** [comment]
+1

**Comment by abhirakshit** [comment]
+1

**Comment by me2bits** [comment]
+1

**Comment by invot** [comment]
+2,000,000,000

**Comment by Ettingshausen** [comment]
+1

**Comment by khacluan** [comment]
+ 1 bill

**Comment by aurelian-scarlat** [comment]
If your box has a class named `select2`, you'll run into trouble because there are some other elements with the same class. So this is wrong:
`$('.select2').select2('destroy');`
The correct way is:
`$('select.select2').select2('destroy');`
Or change the class of the box:
`$('.select-select2').select2('destroy');`
Or even better, use an `id`:
`$('#selectbox').select2('destroy');`

It took me a while to figure this out, I hope it helps somebody.

**Comment by aldeed** [comment]
Merged PR
